//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpful.TextParser.Test.Parser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParserTestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParserTestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helpful.TextParser.Test.Parser.ParserTestResources", typeof(ParserTestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEADER,TEST0001,RONALD,RUSSEL,LIMA,PERU,29,01-01-1988,25000.00
        ///HEADER,TEST0002,ALBERT,RIVER,LIMA,PERU,38,01-01-1979,80000.57
        ///HEADER,TEST0003,EDGAR,BANKS,FORT LEE,USA,29,04-12-1980,500423.2546.
        /// </summary>
        public static string DelimitedParserOnlyOneLevel {
            get {
                return ResourceManager.GetString("DelimitedParserOnlyOneLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEADER,PO001,CATERPILLAR,2017-03-01
        ///DETAIL,01,WHEELS,5,460.50,USD
        ///DETAIL,02,TRUCK,1,50460.56,USD
        ///HEADER,PO002,MAN UNITED,2017-01-01
        ///DETAIL,01,WHEELS,2,200,USD.
        /// </summary>
        public static string DelimitedParserWithChildren {
            get {
                return ResourceManager.GetString("DelimitedParserWithChildren", resourceCulture);
            }
        }
    }
}
